// content.js
// P1 → P2 → P3 integration bridge.

// cycle_id is generated by P1 and is never modified here.

import { processFrame } from "./src/index.js";


// --------------------------------------------------
// P2 perception function
//
// IMPORTANT:
// Replace these calls with the actual P2 functions/files
// if they are exposed under different names.
//
// P2 is responsible for:
//   - DOM extraction
//   - screenshot decoding
//   - YOLO vision
//   - DOM + vision fusion
// --------------------------------------------------

async function runP2Perception(p1Payload) {

  const {
    cycle_id,
    screenshot,
    viewport
  } = p1Payload;


  if (!cycle_id) {
    throw new Error("Missing cycle_id.");
  }

  if (!screenshot) {
    throw new Error("Missing screenshot.");
  }


  // ----------------------------------------------
  // 1. DOM extraction
  // ----------------------------------------------

  const domElements =
    P2DOM.extractAllElements();

  const dom_extracted_at =
    Date.now();


  // ----------------------------------------------
  // 2. Decode screenshot
  // ----------------------------------------------

  const image =
    await loadScreenshotImage(screenshot);


  // ----------------------------------------------
  // 3. Vision inference
  // ----------------------------------------------

  let session =
    P2Vision.getSession();

  if (!session) {
    session =
      await P2Vision.loadVisionModel();
  }

  const visionDetections =
    await P2Vision.runInference(image);


  // ----------------------------------------------
  // 4. DOM + Vision fusion
  // ----------------------------------------------

  const fused =
    P2Fusion.fuseDomAndVision(
      domElements,
      visionDetections
    );


  // ----------------------------------------------
  // 5. Return P2 payload
  // ----------------------------------------------

  return {
    cycle_id,

    dom_extracted_at,

    elements:
      fused.elements,

    vision_only:
      fused.vision_only,

    viewport
  };
}


// --------------------------------------------------
// Decode P1 screenshot
// --------------------------------------------------

function loadScreenshotImage(dataUrl) {

  return new Promise((resolve, reject) => {

    const image =
      new Image();

    image.onload = () => {
      resolve(image);
    };

    image.onerror = () => {
      reject(
        new Error(
          "Failed to decode P1 screenshot."
        )
      );
    };

    image.src = dataUrl;
  });
}


// --------------------------------------------------
// Handle messages from P1
// --------------------------------------------------

chrome.runtime.onMessage.addListener(
  (message, sender, sendResponse) => {


    // ----------------------------------------------
    // P1 asks for current viewport
    // ----------------------------------------------

    if (message?.type === "GET_VIEWPORT") {

      sendResponse({
        scrollX: window.scrollX,
        scrollY: window.scrollY,
        innerWidth: window.innerWidth,
        innerHeight: window.innerHeight
      });

      return false;
    }


    // ----------------------------------------------
    // Ignore unrelated messages
    // ----------------------------------------------

    if (
      message?.type !==
      "P1_CAPTURE_CYCLE"
    ) {
      return;
    }


    const p1Payload =
      message.payload;


    // ----------------------------------------------
    // Validate P1 payload
    // ----------------------------------------------

    if (!p1Payload?.cycle_id) {

      console.error(
        "[Obscura] P1 payload missing cycle_id."
      );

      sendResponse({
        valid: false,
        error: "Missing cycle_id"
      });

      return false;
    }


    if (!p1Payload?.screenshot) {

      console.error(
        "[Obscura] P1 payload missing screenshot."
      );

      sendResponse({
        valid: false,
        error: "Missing screenshot"
      });

      return false;
    }


    console.log(
      "[Obscura] P1 capture received:",
      p1Payload.cycle_id
    );


    // ----------------------------------------------
    // P2 → P3 → response
    // ----------------------------------------------

    (async () => {

      try {

        // ==========================================
        // STEP 1 — P2 perception
        // ==========================================

        const p2Result =
          await runP2Perception(
            p1Payload
          );


        console.log(
          "[Obscura] P2 perception complete:",
          p2Result
        );


        // ==========================================
        // STEP 2 — P3 processing
        // ==========================================

        const p3Result =
          await processFrame({

            // P1's cycle_id remains authoritative.
            frame_id:
              p2Result.cycle_id,

            // Elements come from P2.
            elements:
              p2Result.elements,

            // Original screenshot comes from P1.
            screenshot:
              p1Payload.screenshot
          });


        console.log(
          "[Obscura] P3 processing complete:",
          p3Result
        );


        // ==========================================
        // STEP 3 — Return everything to P1
        // ==========================================

        sendResponse({

          valid: true,

          cycle_id:
            p2Result.cycle_id,

          // P2 result, if useful downstream.
          perception: p2Result,

          // P3 outputs.
          toP4:
            p3Result.toP4,

          toP1:
            p3Result.toP1,

          toP6:
            p3Result.toP6
        });


      } catch (error) {

        console.error(
          "[Obscura] P2/P3 pipeline failed:",
          error
        );


        sendResponse({

          valid: false,

          cycle_id:
            p1Payload.cycle_id,

          error:
            error?.message ||
            "P2/P3 processing failed."
        });
      }

    })();


    // ----------------------------------------------
    // P2/P3 processing is asynchronous.
    // Keep Chrome's message channel open.
    // ----------------------------------------------

    return true;
  }
);